Pages/DetalleReunion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace ingreso_kpi_1.Pages
{
    public class DetalleReunionModel : PageModel
    {

        private IConfiguration configuracion;
        public int IdReunion;
        public string SafetyShare;
        public DataTable TablaReconocimientos;
        public int IdUnidad;

        public DetalleReunionModel(IConfiguration conf)
        {
            configuracion = conf;
        }

        public void OnGet(int id_reunion, int id_unidad)
        {
            IdReunion = id_reunion;
            IdUnidad = id_unidad;
            SafetyShare = obtieneSafetyShare(IdReunion);
            cargaReconocimientos(id_reunion);
        }

        public void OnPostSafetyShare(int id_reunion, string safety_share, int id_unidad)
        {
            IdReunion = id_reunion;
            IdUnidad = id_unidad;

            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "update prueba1.reuniones set safety_share = @safety_share where id = @id_reunion";

            SqlCommand cmd = new SqlCommand(sql, con);

            cmd.Parameters.AddWithValue("@id_reunion", id_reunion);
            cmd.Parameters.AddWithValue("@safety_share", safety_share);

            cmd.ExecuteNonQuery();

            SafetyShare = safety_share;
        }

        private string obtieneSafetyShare(int idReunion)
        {
            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select safety_share from prueba1.reuniones where id = @id_reunion";

            SqlCommand cmd = new SqlCommand(sql, con);

            cmd.Parameters.AddWithValue("@id_reunion", idReunion);

            object resp = cmd.ExecuteScalar();

            SafetyShare = "";

            if (resp != null)
            {
                SafetyShare = (string)resp;
            }

            return SafetyShare;
        }

        private void cargaReconocimientos(int idReunion)
        {
            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select p1.nombre as quien_reconoce, p2.nombre as reconocido, r.pilar, r.motivo " 
                + " from prueba1.reconocimientos r inner join prueba1.personas p1 on r.id_quien_reconoce " + 
                " = p1.id inner join prueba1.personas p2 on r.id_reconocido = p2.id where r.id_reunion = @id_reunion";

            SqlCommand cmd = new SqlCommand(sql, con);

            cmd.Parameters.AddWithValue("@id_reunion", idReunion);

            SqlDataAdapter adapter = new SqlDataAdapter(cmd);

            TablaReconocimientos = new DataTable();

            adapter.Fill(TablaReconocimientos);
        }

        public void OnPostGrabaReconocimiento(int id_unidad, int id_reunion, int quien_reconoce, int reconocido, string pilar, string motivo)
        {
            IdReunion = id_reunion;
            IdUnidad = id_unidad;

            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select max(id) from prueba1.reconocimientos";

            SqlCommand cmd = new SqlCommand(sql, con);

            object resultado = cmd.ExecuteScalar();

            int NuevoId = 1;

            if (resultado !=null)
            {
                NuevoId = (int)resultado + 1;
            }

            sql = "insert into prueba1.reconocimientos(id, id_reunion,id_quien_reconoce, id_reconocido, pilar, motivo) " +
                "values(@id,@id_reunion,@id_quien_reconoce,@id_reconocido,@pilar,@motivo)";

            cmd = new SqlCommand(sql, con);

            cmd.Parameters.AddWithValue("@id", NuevoId);
            cmd.Parameters.AddWithValue("@id_reunion", id_reunion);
            cmd.Parameters.AddWithValue("@id_quien_reconoce", quien_reconoce);
            cmd.Parameters.AddWithValue("@id_reconocido", reconocido);
            cmd.Parameters.AddWithValue("@pilar", pilar);
            cmd.Parameters.AddWithValue("@motivo", motivo);

            cmd.ExecuteNonQuery();

            SafetyShare = obtieneSafetyShare(IdReunion);
            cargaReconocimientos(id_reunion);
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace reportes_io.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace reportes_io.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/IngresoKPI.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Collections.Generic;
using System.Data.SqlClient;

namespace ingreso_kpi_1.Pages
{
    public class IngresoKPIModel : PageModel
    {
        private IConfiguration configuracion;

        public DataTable tablaKPI;
        public DataTable tablaSemanas;
        public DataTable tablaValores;
        public DataTable tablaUnidades;

        public int idKPI = 0;
        public int idUnidad = 0;

        public IngresoKPIModel(IConfiguration conf)
        {
            configuracion = conf;
        }

        public void OnGet()
        {
            cargaControles();
        }

        public void OnPostSelKPI(int Unidad, int kpi) 
        {
            cargaControles();
            cargaValores(kpi,Unidad);
            this.idUnidad = Unidad;
            this.idKPI = kpi;
        }

        public void OnPostSelUnidad(int Unidad)
        {
            cargaControles();
            this.idUnidad = Unidad;
            this.idKPI = 0;
        }


        public void OnPostCargaValor(int kpi, int valor, DateTime fecha, int unidad)
        {

            grabaValor(kpi,fecha,valor,unidad);
            cargaControles();
            cargaValores(kpi,unidad);
            this.idKPI = kpi;
            this.idUnidad= unidad;
        }

        private void grabaValor(int kpi, DateTime fecha, int valor, int unidad)
        {

            int semana = obtieneIdSemana(fecha);

            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select max(id) from prueba1.valores_semanales";

            SqlCommand cmd = new SqlCommand(sql, con);

            int idNuevo = 1;

            try
            {
                idNuevo = (int)cmd.ExecuteScalar()+1;
            }
            catch (Exception e)
            {
                idNuevo = 1;
            }

            // Buscando si ya hay ingresado un valor

            sql = "select id from prueba1.valores_semanales where id_semana = @id_semana and id_kpi = @id_kpi and id_unidad = @unidad ";

            cmd = new SqlCommand(sql, con);
            cmd.Parameters.Add(new SqlParameter("@id_semana", semana));
            cmd.Parameters.Add(new SqlParameter("@id_kpi", kpi));
            cmd.Parameters.Add(new SqlParameter("@unidad", unidad));

            var respuesta = cmd.ExecuteScalar();

            if (respuesta == null)
            {
                sql = "insert into prueba1.valores_semanales(id,id_semana,id_kpi,actual, id_unidad) values(@id,@id_semana,@id_kpi,@actual,@unidad)";

                cmd = new SqlCommand(sql, con);
                cmd.Parameters.Add(new SqlParameter("@id", idNuevo));
                cmd.Parameters.Add(new SqlParameter("@id_semana", semana));
                cmd.Parameters.Add(new SqlParameter("@id_kpi", kpi));
                cmd.Parameters.Add(new SqlParameter("@actual", valor));
                cmd.Parameters.Add(new SqlParameter("@unidad", unidad));

                cmd.ExecuteNonQuery();
            }
            else
            {
                sql = "update prueba1.valores_semanales set actual = @actual where id = @id";

                cmd = new SqlCommand(sql, con);
                cmd.Parameters.Add(new SqlParameter("@id", respuesta));
                cmd.Parameters.Add(new SqlParameter("@actual", valor));

                cmd.ExecuteNonQuery();
            }



        }

        private void cargaValores(int idKPI, int unidad)
        {
            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql;

            sql = "select prueba1.kpi.nombre, vs.id, vs.id_semana, s.inicio_semana, vs.actual, prueba1.unidades.gerencia, prueba1.unidades.superintendencia " +
                "from prueba1.valores_semanales vs inner join prueba1.semanas s " +
                "on vs.id_semana = s.id inner join prueba1.kpi on vs.id_kpi = prueba1.kpi.id " + 
                "inner join prueba1.unidades on prueba1.unidades.id = vs.id_unidad " +
                "where vs.id_kpi = @id_kpi and vs.id_unidad = @unidad order by s.inicio_semana";


            SqlCommand cmd = new SqlCommand(sql, con);
            cmd.Parameters.Add(new SqlParameter("@id_kpi", idKPI));
            cmd.Parameters.Add(new SqlParameter("@unidad", unidad));

            tablaValores = new DataTable();

            SqlDataAdapter adapter = new SqlDataAdapter(cmd);

            adapter.Fill(tablaValores);
        }

        private void cargaControles()
        {
            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select id, nombre from prueba1.kpi order by nombre";

            SqlDataAdapter adapter = new SqlDataAdapter(sql, con);

            tablaKPI = new DataTable();

            adapter.Fill(tablaKPI);

            sql = "select id, inicio_semana from prueba1.semanas";

            tablaSemanas = new DataTable();

            adapter = new SqlDataAdapter(sql, con);

            adapter.Fill(tablaSemanas);

            sql = "select id, gerencia_general, gerencia, superintendencia, nivel " +
                    "from prueba1.unidades where gerencia <> '-' order by gerencia_general, gerencia, superintendencia";

            tablaUnidades = new DataTable();

            adapter = new SqlDataAdapter(sql, con);

            adapter.Fill(tablaUnidades);
        }

        private int obtieneIdSemana(DateTime fecha)
        {
            int diff = fecha.DayOfWeek - DayOfWeek.Monday;

            if (diff < 0)
            {
                diff += 7;
            }


            DateTime inicioSemana = fecha.AddDays(-1 * diff).Date;

            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select id from prueba1.semanas where inicio_semana = @inicio_semana";

            SqlCommand cmd = new SqlCommand(sql, con);

            cmd.Parameters.Add(new SqlParameter("@inicio_semana", inicioSemana));

            object id = cmd.ExecuteScalar();

            if (id != null)
            {
                return (int)id;
            }

            return 0;
        }
    }
}

Pages/KPIReunion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ingreso_kpi_1.Pages
{
    public class KPIReunionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/NuevaReunion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ingreso_kpi_1.Pages
{
    public class NuevaReunionModel : PageModel
    {
        public int idUnidad;

        public void OnGet()
        {
        }

        public void OnPost(int id_unidad) 
        {
            
        }
    }
}

Pages/NuevoReconocimiento.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;

namespace ingreso_kpi_1.Pages
{
    public class NuevoReconocimientoModel : PageModel
    {

        private IConfiguration configuracion;
        public int IdReunion;
        public int IdUnidad;
        public DataTable TablaPersonas;

        public NuevoReconocimientoModel(IConfiguration conf)
        {
            configuracion = conf;
        }

        public void OnGet(int id_unidad, int id_reunion)
        {
            IdUnidad = id_unidad;
            IdReunion = id_reunion;
            cargaPersonas();
        }

        private void cargaPersonas()
        {
            TablaPersonas = new DataTable();

            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select id, nombre, id_unidad, rol " +
                    "from prueba1.personas where id_unidad = @id_unidad order by nombre";


            SqlCommand cmd = new SqlCommand(sql, con);
            cmd.Parameters.Add(new SqlParameter("@id_unidad", IdUnidad));

            TablaPersonas = new DataTable();

            SqlDataAdapter adapter = new SqlDataAdapter(cmd);

            adapter.Fill(TablaPersonas);
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace reportes_io.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Pages/Reunion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;

namespace ingreso_kpi_1.Pages
{
    public class ReunionModel : PageModel
    {
        private IConfiguration configuracion;
        public DataTable TablaUnidades;
        public int IdUnidad;
        public DataTable TablaReuniones;

        public ReunionModel(IConfiguration conf)
        {
            configuracion = conf;
        }

        private void cargaUnidades()
        {
            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select id, gerencia_general, gerencia, superintendencia, nivel " +
                    "from prueba1.unidades where gerencia <> '-' order by gerencia_general, gerencia, superintendencia";

            TablaUnidades = new DataTable();

            SqlDataAdapter adapter = new SqlDataAdapter(sql, con);

            adapter.Fill(TablaUnidades);
        }

        public void OnGet()
        {
            cargaUnidades();
        }

        public void OnPostSelUnidad(int id_unidad)
        {
            IdUnidad = id_unidad;
            cargaUnidades();
            cargaReuniones(IdUnidad);
        }

        public void OnPostNuevaReunion(int id_unidad, string tipo_reunion, DateTime fecha)
        {
            IdUnidad = id_unidad;

            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select max(id) from prueba1.reuniones";

            SqlCommand cmd = new SqlCommand(sql, con);

            object respuesta = cmd.ExecuteScalar();

            int id = 1;

            if (respuesta != null)
            {
                id = (int)respuesta + 1;
            }

            sql = "insert into prueba1.reuniones(id, tipo, id_unidad, fecha) values(@id, @tipo, @id_unidad, @fecha)";

            cmd = new SqlCommand(sql, con);
            cmd.Parameters.AddWithValue("@id", id);
            cmd.Parameters.AddWithValue("@tipo", tipo_reunion);
            cmd.Parameters.AddWithValue("@id_unidad", id_unidad);
            cmd.Parameters.AddWithValue("@fecha", fecha);

            cmd.ExecuteNonQuery();

            cargaUnidades();
            cargaReuniones(IdUnidad);

        }




        public void cargaReuniones(int IdUnidad)
        {
            string con_str = configuracion["con_str"];

            SqlConnection con = new SqlConnection(con_str);
            con.Open();

            string sql = "select id, fecha, tipo, estado, actual " +
                    "from prueba1.reuniones where id_unidad = @id_unidad";


            SqlCommand cmd = new SqlCommand(sql, con);
            cmd.Parameters.Add(new SqlParameter("@id_unidad",IdUnidad));

            TablaReuniones = new DataTable();

            SqlDataAdapter adapter = new SqlDataAdapter(cmd);

            adapter.Fill(TablaReuniones);
        }
    }
}

Pages/DetalleReunion.cshtml
@page
@model ingreso_kpi_1.Pages.DetalleReunionModel
@using System.Data
@{
}

<h1>Detalle Reunión</h1>

Id = @Model.IdReunion


<h2>Safety Share</h2>

<form asp-page-handler="SafetyShare" method="post">

    <div class="row">
        <div class="col-6">

            <label class="col-form-label" for="safety_share">Safety Share</label>
            <textarea class="form-control mb-3" name="safety_share">@Model.SafetyShare</textarea>

        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-5">
            <button class="btn btn-primary form-control ">Actualizar Safety Share</button>
        </div>
    </div>

    <input type="hidden" name="id_reunion" value="@Model.IdReunion" />
    <input type="hidden" name="id_unidad" value="@Model.IdUnidad" />

</form>

<h2>Reconocimientos</h2>

<table class="table">

    <thead>
        <tr>
            <th>Num.</th>
            <th>Quién Reconoce</th>
            <th>Quién es Reconocido</th>
            <th>Pilar</th>
            <th>Motivo</th>
        </tr>
    </thead>

    <tbody>
        @{
            int i = 0;
        }
        @foreach(DataRow fila in Model.TablaReconocimientos.Rows)
        {
            i = i + 1;
            <tr>
                <td>@i</td>
                <td>@fila["quien_reconoce"]</td>
                <td>@fila["reconocido"]</td>
                <td>@fila["pilar"]</td>
                <td>@fila["motivo"]</td>
            </tr>
        }
    </tbody>

</table>

<a asp-page="NuevoReconocimiento" asp-route-id_unidad="@Model.IdUnidad" asp-route-id_reunion="@Model.IdReunion" class="btn btn-primary">Nuevo Reconocimiento</a>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Inicio";
}

<div class="text-center">
    <h1 class="display-4">Ingreso Datos KPI</h1>
    <p> ambiente de pruebas para proyecto Optimización de Reportes.</p>
</div>

Pages/IngresoKPI.cshtml
@page
@model ingreso_kpi_1.Pages.IngresoKPIModel
@using System.Data
@{
}

<h1>Ingreso de KPI</h1>

<div class="container">

    <form asp-page-handler="SelUnidad" method="post">
        <div class="row">
            <div class="col-6 mb-3">
                <label for="kpi" class="form-label">Unidad</label>

                <!-- Carga Unidades -->

                <select class="form-select" name="Unidad">
                    @foreach (DataRow fila in Model.tablaUnidades.Rows)
                    {
                        string nombre;

                        if (fila["superintendencia"].ToString() == "-")
                        {
                            nombre = "[Gerencia:] " + fila["gerencia"].ToString();
                        }
                        else
                        {
                            nombre = "[Gerencia] " + fila["gerencia"].ToString() + " [Superint.] " + fila["superintendencia"].ToString();
                        }

                        if ((int)fila["id"] == Model.idUnidad)
                        {
                            <option value="@fila["id"]" selected>@nombre</option>
                        }
                        else
                        {
                            <option value="@fila["id"]">@nombre</option>
                        }
                    }
                </select>
            </div>

            <div class="col-3 mb-3 align-self-end">
                <input type="submit" value="Seleccionar Unidad" class="btn btn-primary form-control ">
            </div>

        </div>
    </form>

    <form asp-page-handler="SelKPI" method="post">
        <div class="row">
            <div class="col-6 mb-3">
                <label for="kpi" class="form-label">Nombre KPI</label>
                <select class="form-select" name="kpi">
                    @foreach (DataRow fila in Model.tablaKPI.Rows)
                    {
                        if((int)fila["id"]==Model.idKPI)
                        {
                            <option value="@fila["id"]" selected>@fila["nombre"]</option>
                        }
                        else
                        {
                            <option value="@fila["id"]">@fila["nombre"]</option>
                        }
                    }
                </select>
            </div>

            <input type="hidden" name="Unidad" value="@Model.idUnidad" />

            <div class="col-3 mb-3 align-self-end">

                @if(Model.idUnidad == 0)
                {
                    <input type="submit" value="Seleccionar KPI" class="btn btn-primary form-control " disabled>
                }
                else
                {
                    <input type="submit" value="Seleccionar KPI" class="btn btn-primary form-control ">
                }


                
            </div>

        </div>
    </form>

    <form asp-page-handler="cargaValor" method="post">

        <input type="hidden" name="kpi" value="@Model.idKPI" />
        
        <input type="hidden" name="unidad" value="@Model.idUnidad" />
        
        <div class="row">

            <div class="col-3 mb-3">

                <label for="fecha" class="form-label">Semana</label>

                <input type="date" class="form-control" name="fecha" />

            </div>

            <div class="col-3 mb-3">
                <label for="valor" class="form-label">Valor</label>
                <input type="number" class="form-control" name="valor" />
            </div>

            <div class="col-3 mb-3  align-self-end">

                @if(Model.idKPI !=0 )
                {
                    <input type="submit" class="btn btn-primary form-control" value="Ingresar Valor" />
                }
                else
                {
                    <input type="submit" class="btn btn-primary form-control" value="Ingresar Valor" disabled />
                }

            </div>

        </div>
    </form>

    @if(Model.idKPI != 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Num.</th>
                    <th>Nombre KPI</th>
                    <th>Inicio de Semana</th>
                    <th>Valor</th>
                    <th>Gerencia</th>
                    <th>Superintendencia</th>
                </tr>
            </thead>
            <tbody>

                @if (Model.tablaValores != null && Model.tablaValores.Rows.Count > 0)
                {
                    int i = 0;
                    foreach (DataRow fila in Model.tablaValores.Rows)
                    {
                        i = i + 1;
                        <tr>
                            <td>@i</td>
                            <td>@fila["nombre"]</td>
                            <td>@DateTime.Parse(fila["inicio_semana"].ToString()).ToString("dd-MM-yyyy")</td>
                            <td>@fila["actual"]</td>
                            <td>@fila["gerencia"]</td>
                            <td>@fila["superintendencia"]</td>
                        </tr>
                    }
                }


            </tbody>
        </table>
    }



</div>

Pages/KPIReunion.cshtml
@page
@model ingreso_kpi_1.Pages.KPIReunionModel
@{
}


<h1>Ingreso KPI Reunión</h1>

<table class="table">
    <thead>
        <tr>
            <th class ="col-2">
                Num.
            </th>
            <th class="col-3">
                KPI
            </th>
            <th class="col-2">
                Valor Semanal
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                1
            </td>
            <td>
                KPI 1
            </td>
            <td>
                <input type="number" class="form-control"/>
            </td>

        </tr>
        <tr>
            <td>
                2
            </td>
            <td>
                KPI 2
            </td>
            <td>
                <input type="number" class="form-control" />
            </td>

        </tr>
        <tr>
            <td>
                3
            </td>
            <td>
                KPI 3
            </td>
            <td>
                <input type="number" class="form-control" />
            </td>

        </tr>
        <tr>
            <td>
                4
            </td>
            <td>
                KPI 4
            </td>
            <td>
                <input type="number" class="form-control" />
            </td>

        </tr>
    </tbody>
</table>

            <button class="btn btn-primary" > Actualizar </button>

Pages/NuevaReunion.cshtml
@page
@model ingreso_kpi_1.Pages.NuevaReunionModel
@{
}


<h1>Nueva Reunión</h1>

<form asp-page-handler="NuevaReunion" method="post">

    <div class="row">

        <div class="col-3">
            <label for="fecha" class="col-form-label">Fecha</label>
            <input type="date" class="form-control mb-3" name="fecha" />


            <label for="tipo_reunion" class="col-from-label">Tipo de Reunión</label>

            <div class="input-group mb-3">
                <div class="form-check mb-3 me-3">
                    <input type="radio" class="form-check-input mb-3" name="tipo_reunion" value="MIP" />
                    <label for="tipo_reunion" class="form-check-label">MIP</label>
                </div>

                <div class="form-check">
                    <input type="radio" class="form-check-input" name="tipo_reunion" value="MOP" />
                    <label for="tipo_reunion" class="form-check-label">MOP</label>
                </div>
            </div>

            <label class="col-form-label">Asistentes</label>

            <label for="nombre_asistente" class="col-form-label">Nombre</label>
            <input type="text" name="nombre-asistente" class="form-control mb-3" />

            <button class="form-control btn btn-secondary mb-3">Agregar Asistente</button>

            <button class="form-control btn btn-primary mb-3">Grabar Reunión</button>
        </div>
    </div>

    <input type="hidden" name="id_unidad" value="" />

</form>

Pages/NuevoReconocimiento.cshtml
@page
@model ingreso_kpi_1.Pages.NuevoReconocimientoModel
@using System.Data

<h1>Nuevo Reconocimiento</h1>

<form asp-page="DetalleReunion" asp-page-handler="GrabaReconocimiento" method="post">
    
    <input type="hidden" name="id_reunion" value="@Model.IdReunion" />
    <input type="hidden" name="id_unidad" value="@Model.IdUnidad" />

    <div class="row">

        <div class="col-4 mb-3">
            <label class="col-form-label" for="quien_reconoce">Quien Reconoce</label>
            <select class="form-select" name="quien_reconoce">
                @foreach(DataRow fila in Model.TablaPersonas.Rows)
                {
                    <option value="@fila["id"]">@fila["nombre"]</option>
                }
            </select>
        </div>

        <div class="col-4 mb-3">
            <label class="col-form-label" for="reconocido">Reconocido</label>
            <select class="form-select" name="reconocido">
                @foreach (DataRow fila in Model.TablaPersonas.Rows)
                {
                    <option value="@fila["id"]">@fila["nombre"]</option>
                }
            </select>
        </div>

        <div class="col-4 mb-3">
            <label class="col-form-label" for="pilar">Pilar</label>
            <select class="form-select" name="pilar">
                <option></option>
                <option>Persona</option>
                <option>Performance</option>
                <option>Salud & Seguridad</option>
            </select>
        </div>

    </div>

    <div class="row">
        <div class="col mb-3">
            <label class="col-form-label" for="motivo">Motivo</label>
            <textarea type="text" class="form-control" name="motivo"></textarea>
        </div>
    </div>

    <div class="row">
        <div class="col-4 mb-3">
            <button class="btn btn-primary">Grabar Reconocimiento</button>
        </div>
    </div>

</form>